version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/TaskManager
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: laravel-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
#        volumes:
#            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
