services:
    # Application Service (PHP-FPM)
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/TaskManager
        working_dir: /var/www/TaskManager
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
        depends_on:
            - mysql
        networks:
            - taskmanager

    # MySQL Service
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - taskmanager

    # Web Server (Nginx)
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/TaskManager
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - taskmanager

volumes:
    mysql_data:

networks:
    taskmanager:
        driver: bridge

