services:
    # Application Service (PHP-FPM)
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/TaskManager  # Correct the volume mount
        ports:
            - "9000:9000"  # PHP-FPM listening on 9000 inside the container
        working_dir: /var/www/TaskManager
        depends_on:
            - db  # Ensure that the DB service is started before this one

    # MySQL Service
    db:
        image: mysql:8
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
    # Web Server (Nginx)
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8081:80"  # Exposing Nginx on port 8081
        volumes:
            - .:/var/www/TaskManager  # Correct volume for Nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx config

